/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_convertererror_free: (a: number, b: number) => void;
export const __wbg_deepdive_free: (a: number, b: number) => void;
export const __wbg_deepdivemission_free: (a: number, b: number) => void;
export const __wbg_deepdiveresult_free: (a: number, b: number) => void;
export const __wbg_get_convertererror_message: (a: number) => [number, number];
export const __wbg_get_convertererror_type: (a: number) => [number, number];
export const __wbg_get_deepdive_biome: (a: number) => number;
export const __wbg_get_deepdivemission_complexity: (a: number) => number;
export const __wbg_get_deepdivemission_duration: (a: number) => number;
export const __wbg_get_deepdivemission_mutator: (a: number) => number;
export const __wbg_get_deepdivemission_warning: (a: number) => number;
export const __wbg_get_deepdiveresult_elite: (a: number) => number;
export const __wbg_get_deepdiveresult_normal: (a: number) => number;
export const __wbg_get_deepdiveresult_seed: (a: number) => number;
export const __wbg_seed_free: (a: number, b: number) => void;
export const deepdive_missions: (a: number) => [number, number];
export const deepdivemission_primaryObjective: (a: number) => any;
export const deepdivemission_secondaryObjective: (a: number) => any;
export const generate: (a: number) => [number, number, number];
export const seed_as_u32: (a: number) => number;
export const seed_new: (a: number) => number;
export const __wbg_get_deepdive_name: (a: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
